[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[context.production]
  command = "pip install -r requirements.txt"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
